## **Tensorflow:**
It is an open source deeplearning library developed by google
It takes multidimensional array(tensors) as input.

#In this notebook, we will cover the fundamentals of tensors using TF

#Introduction to tensors

In [9]:
# Import TF

import tensorflow as tf
print(tf.__version__)

2.8.2


##Scalar

In [10]:
#creating scalar with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

###Scalar Dimension

In [11]:
#checking the dimensions of scalar using ndim-no.of dimensions

scalar.ndim

0

##Vector

In [12]:
#creating a vector 

vector = tf.constant([8, 12])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 8, 12], dtype=int32)>

###Vector Dimension

In [13]:
#checking the dimension of the vector

vector.ndim

1

##Matrix

In [14]:
#creating a matrix having more than one dimension

matrix = tf.constant([[22, 21],
                     [12, 21]])

###Matrix Dimension

In [15]:
#checking the dimension of the matrix

matrix.ndim

2

In [16]:
#creating another matrix

another_matrix = tf.constant([[12., 21.],
                   [22., 21.],
                   [33., 31.]], dtype = tf.float16)       #changing the datatype to float

In [17]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[12., 21.],
       [22., 21.],
       [33., 31.]], dtype=float16)>

In [18]:
#checking the dimension of another_matrix

another_matrix.ndim

2

##Tensor

In [19]:
#creating a tensor

tensor = tf.constant([[[1,2,3],
                        [4,5,6]],
                        [[5,6,7],
                       [7,8,9]],
                       [[8,9,10],
                        [9,10,11]]])

In [20]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 5,  6,  7],
        [ 7,  8,  9]],

       [[ 8,  9, 10],
        [ 9, 10, 11]]], dtype=int32)>

###Tensor Dimension

In [21]:
#checking the dimension of the tensor

tensor.ndim

3

###Zeroes Tensor

In [22]:
#creating tensor of zeros

z_tensors = tf.zeros((2,2))
z_tensors

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

###Ones Tensor

In [23]:
#creating tensor of ones

ones_tensor = tf.ones((2,2))
ones_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

###Diagonal 1's Tensor

In [24]:
#creating a tensor with diagonal elements as 1, using eye()

diag_tensor = tf.eye(3)
diag_tensor

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [25]:
ones_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

###Casting Datatype

In [26]:
#converting the datatype of the tensor
tensor_cast = tf.cast(ones_tensor, dtype = tf.int32)
tensor_cast

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>

###Summary:
* Scalar is a single number
* Vector is a number with direction 
* Matrix is a 2-d array of numbers
* Tensor is an n-dimensional array of numbers(where, n=0d tensor:scalar, n=1d tensor:vector)

##tf.variable

 **Creating tensor with tf.Variable**

In [27]:
#creating a tensor with tf.Variable

changeable_tensor = tf.Variable([10,11])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 11], dtype=int32)>

##tf.constant

In [28]:
#comparing with tf.constant 

unchangeable_tensor = tf.constant([10,10])
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

##changing the elements

In [29]:
#changing the elements of changeable_tensor

changeable_tensor[0] = 8
changeable_tensor       #we will be getting an error and it is solved in the next code cell

TypeError: ignored

In [30]:
#changing the value of changeable tensor using .assign()

changeable_tensor[0].assign(8)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 8, 11], dtype=int32)>

In [32]:
#let's try to change the elements of unchangeable_tensor

unchangeable_tensor[0].assign(8)
unchangeable_tensor

AttributeError: ignored

In [33]:
#since the unchangeable_tensor is a constant tensor made by tf.constant(), it's element values cannot be changed.

##Random tensor

**Creating Random tensors**

Random tensors are the tensors which contains random numbers of some arbitary size.

In [34]:
#creating random normally distributed tensor

random_nrml = tf.random.normal((3,3), mean =0, stddev=1)
random_nrml

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.1459079 ,  2.0345483 , -0.49514037],
       [-0.36501387, -1.9412805 ,  0.7273292 ],
       [ 1.4374158 , -0.3731767 ,  0.58636934]], dtype=float32)>

In [35]:
#creating two similar randoms tensors

random_tensor1 = tf.random.Generator.from_seed(42)        #setting the seed for reproducibility
random_tensor1 = random_tensor1.normal(shape=(3,2))
random_tensor2 = tf.random.Generator.from_seed(42)        #setting the seed for reproducibility
random_tensor2 = random_tensor2.normal(shape=(3,2))

In [36]:
random_tensor1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [37]:
random_tensor2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [38]:
#checking if the two random tensors created are equal or not

random_tensor1 == random_tensor2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

##Shuffling

**Shuffling the order of elements in a tensor**

it is valuable for when you want to shuffle your data so that the inherent order doesn't effect learning

In [39]:
un_shuffled = tf.constant([[1,2],
                           [3,4],
                           [5,6],
                           [7,8]])

In [40]:
un_shuffled


<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [41]:
#let's shuffle the un_shuffled tensor

tf.random.shuffle(un_shuffled)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

##Global and operational seed

In [42]:
#If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.
#we use both global and operation level random seeds to keep our shuffled tensors in the same order.

tf.random.set_seed(22)        #global level random seed
tf.random.shuffle(un_shuffled, seed = 22)       #operation level random seed

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2],
       [7, 8]], dtype=int32)>

##Numpy to Tensors

**Turning numpy arrays to tensors:**
because, tensors runs on a GPU which makes them fast computing than numpy numbers


In [43]:
import numpy as np

#creating an array between the range(1,22)

array1 = np.arange(1,22, dtype = np.int32)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21], dtype=int32)

In [44]:
#converitng numpy arrays into tensors

A = tf.constant(array1)
A

<tf.Tensor: shape=(21,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21], dtype=int32)>

##Reshaping

In [45]:
#reshaping the numpy tensor:

A = tf.reshape(array1, shape = (1,3,7))
A

<tf.Tensor: shape=(1, 3, 7), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 20, 21]]], dtype=int32)>

In [46]:
1*3*7       #will be equal to the total no.of elements in the array

21

In [47]:
A.ndim

3

##Range

In [48]:
#creating a tensor of range(10)

x = tf.range(10)
x

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

##Delta(Step count)

In [49]:
#creating a tensor of delta(step count) = 3 within the range(1,23)

x = tf.range(start=1, limit = 23, delta = 3)
x

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 1,  4,  7, 10, 13, 16, 19, 22], dtype=int32)>

##Attributes

**Getting information from the tensors:**
Attributes:
1.   Shape: Length(no.of elements) of each of the dimensions of a tensor.
2.   Rank: The no.of tensor dimensions. Like, scalar rank=0, vector rank=1, matrix rank=2, a tensor rank = n
3.   Axis or dimension: Its a particular dimension of a tensor
4.   Size: Total no.of items in the tensor.
5.   Datatype: Tells the type of data

In [50]:
#creating a tensor of Rank(4)-4d 

r4_tensor = tf.ones(shape = [2,3,4,5])
r4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [51]:
r4_tensor.ndim

4

###Shape

In [52]:
#shape of the tensor

r4_tensor.shape

TensorShape([2, 3, 4, 5])

###Rank

In [53]:
#rank of the tensor

r4_tensor.ndim

4

###Dimension

In [54]:
#dimension of the tensor

r4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

###Datatype

In [55]:
#datatype of the tensor

r4_tensor.dtype

tf.float32

###Size

In [56]:
#size of the tensor

tf.size(r4_tensor).numpy()      #2*3*4*5=120

120

In [57]:
#printing the elements along the 0 axis:

print("the elements along the 0 axis:",r4_tensor.shape[0])

the elements along the 0 axis: 2


In [58]:
#printing the elements along the last axis:

print("the elements along the 0 axis:",r4_tensor.shape[-1])

the elements along the 0 axis: 5


##Indexing

**Indexing:**
Tensors can be indexed or sliced just like python lists.

In [59]:
#simple list indexing

s_list = [1,2,3,4,5]
s_list[:3]

[1, 2, 3]

In [60]:
#getting the first 2 elements of each dimension from r4_tensor

r4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [61]:
#getting the first element from each dimension of each index except for the last one.

r4_tensor[:1, :1, :1, :]        #getting all the elements from the last one(:)


<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[1., 1., 1., 1., 1.]]]], dtype=float32)>

In [62]:
#creating rank 2 tensor

r2_tensor = tf.constant([[1,2],
                         [3,4]])
r2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [63]:
#getting the last element from simple list

s_list
print("The last element of the simple list is:", s_list[-1])

The last element of the simple list is: 5


In [64]:
#getting the last element of each of our row of r2_tensor

r2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

##Adding Extra Dimension

In [65]:
#adding extra dimension to our r2_tensor

r3_tensor = r2_tensor[:, :, tf.newaxis]       #this can also be written as:r2_tensor[..., tf.newaxis]
print("the actual shape of r2_tensor is:", r2_tensor.shape)
print("the shape of r3_tensor after adding an extra/new dimension to the r2_tensor is:", r3_tensor.shape)

the actual shape of r2_tensor is: (2, 2)
the shape of r3_tensor after adding an extra/new dimension to the r2_tensor is: (2, 2, 1)


In [66]:
#alternative to tf.newaxis: tf.expand_dims

tf.expand_dims(r2_tensor, axis = -1)        #-1 means expand the final axis


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [67]:
tf.expand_dims(r2_tensor, axis = 0)       #expanding the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

In [68]:
r2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

##Tensor Operations

**Tensor operations:** Manipulating the tensors using the basic operations:
 **+, -, *, /**

###Addition

In [69]:
#adding values to a tensor using addition operator

tensor = tf.constant([[1,2], [3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [70]:
#viewing the original tensor

tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [71]:
#using the in-built function for addition

tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

###Subtraction

In [72]:
#subtraction of tensors

tensor - 1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3]], dtype=int32)>

###Multiplication

In [73]:
#multiplication of tensors

tensor*100

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 200],
       [300, 400]], dtype=int32)>

In [74]:
#using the in-built function for multiplication

tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

###Division

In [75]:
#dividing the tensors

tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.5, 1. ],
       [1.5, 2. ]])>

###Matrix Multiplication

**Matrix Multiplication:**
It is one of the most common tensor operations.


In [76]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [77]:
#matrix multiplication

tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [78]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [79]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [80]:
#Matrix multiplication with python operator "@"

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [81]:
tensor.shape

TensorShape([2, 2])

In [82]:
x = tf.constant([[1,2,3,],
                 [4,5,6]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [83]:
y = tf.constant([[1,2],
                 [2,3]])
y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3]], dtype=int32)>

In [85]:
x @ y

InvalidArgumentError: ignored

**There are two rules, the tensors need to satisfy to do a matrix multiplication:**


1.   The inner dimension of the matrix should match
2.   The resulting matrix will have the shape of the inner dimensions.



In [86]:
y @ x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [14, 19, 24]], dtype=int32)>

In [87]:
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

###Transpose

In [88]:
#transposing a matrix

tf.transpose(x)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [89]:
#viewing the difference of transposing a matrix from reshaping it

tf.reshape(x, shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [90]:
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [91]:
y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3]], dtype=int32)>

In [92]:
#doing matrix multiplication with transpose rather than reshape

tf.transpose(x) @ y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 9, 14],
       [12, 19],
       [15, 24]], dtype=int32)>

In [93]:
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [94]:
x = tf.transpose(x)
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [95]:
y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3]], dtype=int32)>

###Dot product

**Dot Product:**
 It is also known as matrix multiplication.
 It is done by using:


1.   tf.matmul()
2.   @
3.   tf.tensordot()



In [96]:
z = tf.tensordot(x, y, axes=1)
z

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 9, 14],
       [12, 19],
       [15, 24]], dtype=int32)>

In [97]:
z.ndim

2

In [98]:
p = tf.tensordot(x, y, axes=0)
p

<tf.Tensor: shape=(3, 2, 2, 2), dtype=int32, numpy=
array([[[[ 1,  2],
         [ 2,  3]],

        [[ 4,  8],
         [ 8, 12]]],


       [[[ 2,  4],
         [ 4,  6]],

        [[ 5, 10],
         [10, 15]]],


       [[[ 3,  6],
         [ 6,  9]],

        [[ 6, 12],
         [12, 18]]]], dtype=int32)>

In [99]:
p.ndim

4

In [100]:
#displaying the normal, transpose and reshaped matrices of x

print("Normal 'x' matrix: \n", x)
print("Transpose of 'x' matrix: \n", tf.transpose(x))
print("Reshaped 'x' matrix: \n", tf.reshape(x, shape=(2,3)))

Normal 'x' matrix: 
 tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
Transpose of 'x' matrix: 
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Reshaped 'x' matrix: 
 tf.Tensor(
[[1 4 2]
 [5 3 6]], shape=(2, 3), dtype=int32)


In [101]:
tf.reshape(x, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 4, 2],
       [5, 3, 6]], dtype=int32)>

In [102]:
tf.reshape(x, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 4, 2],
       [5, 3, 6]], dtype=int32)>

##Aggregating tensor

**Aggregating tensor:**
 Condensing them from multiple values down to a smaller amount of values.

In [103]:
abs_val = tf.constant([-1, -2, 3])
abs_val

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-1, -2,  3], dtype=int32)>

###Absolute value

In [104]:
#getting the absolute values of abs_val: converting negative numbers into positive: mod

tf.abs(abs_val)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [105]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

###Maximum

In [106]:
#getting the maximum 

tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [107]:
tf.reduce_max(tensor).numpy()

4

###Minimum

In [108]:
#getting the minimum

tf.reduce_min(tensor).numpy()

1

###Sum

In [109]:
#getting the sum

tf.reduce_sum(tensor).numpy()

10

###Mean

In [110]:
#getting the mean

tf.reduce_mean(tensor).numpy()

2

###Variance

In [111]:
#getting the variance of our tensor
# to get the variance, the tensor should be of real or complex type.


import tensorflow_probability as tfp

tfp.stats.variance(abs_val).numpy()

4

In [112]:
#getting the variance after converting the tensor to real or complex type, float

tf.math.reduce_variance(tf.cast(tensor, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=1.25>

###Standard deviation

In [113]:
#getting the standard deviation

tf.math.reduce_std(tf.cast(tensor, dtype= tf.float32)).numpy()

1.1180339

##Finding position of max and min

**Finding the positional maximum and minimum of a tensor:**


In [114]:
#creating a random tensor

tf.random.set_seed(42)
random_t = tf.random.uniform(shape=[50])
random_t

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [115]:
#Finding the position of maximum element in a tensor

tf.argmax(random_t).numpy()

42

In [116]:
random_t[42]      

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [117]:
#we can get the value from the position of maximum element by:
random_t[tf.argmax(random_t)].numpy()


0.9671384

In [118]:
tf.reduce_max(random_t).numpy()

0.9671384

In [119]:
#Finding the position of minimum element in a tensor

tf.argmin(random_t)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [120]:
#getting the value from the minimum position

random_t[tf.argmin(random_t)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

##Squeezing

**Squeezing a tensor:**
 Removing all single dimensions.

In [121]:
rt = tf.reshape(random_t, shape=(1,1,1,1, 50))
rt

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [122]:
rt.shape

TensorShape([1, 1, 1, 1, 50])

In [123]:
#removing dimensions of size 1 from the shape of a tensor

rt_squeezed = tf.squeeze(rt)
rt_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [124]:
rt_squeezed.shape


TensorShape([50])

##One-Hot Encoding

**One-hot encoding tensors:**


In [125]:
#create a list of indices

some_lst = [0,1,2,3]        #could be indices of tea, coffee, milk, juice
depth = 4

In [126]:
#encoding each of the values of some_lst

tf.one_hot(some_lst, depth)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [127]:
#encoding by specifying some custom values:

tf.one_hot(some_lst, depth, on_value = 'present', off_value = 'absent')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'present', b'absent', b'absent', b'absent'],
       [b'absent', b'present', b'absent', b'absent'],
       [b'absent', b'absent', b'present', b'absent'],
       [b'absent', b'absent', b'absent', b'present']], dtype=object)>

**Finding log, square and square root values:**

In [128]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

##Square value

In [129]:
#finding the square value

sq_t = tf.square(tensor)
sq_t

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

##Square Root value

In [130]:
#finding the square root values of the tensor

tf.sqrt(tf.cast(sq_t, dtype = tf.float32))        #input type should be of float

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

##Log value

In [131]:
#finding the log

tf.math.log(tf.cast(tensor, dtype = tf.float32))        #input type should be of float

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.       , 0.6931472],
       [1.0986123, 1.3862944]], dtype=float32)>

##Tensors and numpy

In [132]:
#creating a tensor directly from a numpy array

np_t = tf.constant(np.array([1,2,3,4]))
np_t

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [133]:
type(np_t)

tensorflow.python.framework.ops.EagerTensor

In [134]:
#converting tensor to numpy array

np_a = np.array(np_t)
np_a

array([1, 2, 3, 4])

In [135]:
type(np_a)

numpy.ndarray

In [136]:
#converting tensor to numpy array directly
npa = np_t.numpy()
npa

array([1, 2, 3, 4])

In [137]:
type(npa)

numpy.ndarray

In [138]:
print(npa)
print("1st element: ",np_t.numpy()[0])
print("2nd element: ",np_t.numpy()[1])
print("3rd element: ",np_t.numpy()[2])
print("4th element: ",np_t.numpy()[3])

[1 2 3 4]
1st element:  1
2nd element:  2
3rd element:  3
4th element:  4


In [139]:
#checking the default dtypes of numpy and tensor

numpy_a = tf.constant(np.array([1,2,3,4]))
tensor_a = tf.constant([1., 2., 3.])
numpy_a.dtype, tensor_a.dtype

(tf.int64, tf.float32)

##GPU and TPU

**GPU:** Graphic Processing Unit: It is a specialized electronic circuit designed to rapidly manipulate, process and alter memory.

**TPU:** Tensor Processing Unit: It is an AI accelerator Application-Specific Integrated Circuit(ASIC), developed by Google for neural network machine learning.

###Access to GPU

**Finding access to GPU:**

In [140]:
#checking the type of processor

tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [141]:
 #checking for GPU

tf.config.list_physical_devices("GPU")


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [142]:
#It says that there isn't any GPU

**Steps to set to GPU:**


1.   click on 'Runtime'
2.   select 'Change runtime type'
3.   in 'Hardware accelerator': select 'GPU'

In [143]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

###GPU type

In [144]:
#check what type of GPU you are using

!nvidia-smi

Sat Aug 20 09:00:34 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P0    26W /  70W |    286MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

#so, we get to know that we are using Tesla T4 GPU with almost 16GB of memory
#**CUDA:** Compute Unified Device Architecture, is a kind of interface between the GPU and the tensorflow code which makes our tensorflow code run really really fast...

If you have access to a CUDA enabled GPU, then TensorFlow will automatically use it whenever possible.